// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForBookImage() {
  return window['go']['main']['App']['AskForBookImage']();
}

export function AskForBookPDF() {
  return window['go']['main']['App']['AskForBookPDF']();
}

export function CreateBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBook'](arg1, arg2, arg3);
}
