// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForBookImage() {
  return window['go']['main']['App']['AskForBookImage']();
}

export function AskForBookPDF() {
  return window['go']['main']['App']['AskForBookPDF']();
}

export function CheckBookExist(arg1) {
  return window['go']['main']['App']['CheckBookExist'](arg1);
}

export function CreateBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBook'](arg1, arg2, arg3);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBookPDFData(arg1) {
  return window['go']['main']['App']['GetBookPDFData'](arg1);
}

export function GetBooksCount() {
  return window['go']['main']['App']['GetBooksCount']();
}

export function GetHomeBooks() {
  return window['go']['main']['App']['GetHomeBooks']();
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function OpenImage(arg1) {
  return window['go']['main']['App']['OpenImage'](arg1);
}

export function UpdateLastReaded(arg1) {
  return window['go']['main']['App']['UpdateLastReaded'](arg1);
}

export function UpdateProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2);
}
